// <auto-generated />
using System;
using Innovation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Innovation.Data.Migrations
{
    [DbContext(typeof(SiloDbContext))]
    [Migration("20260901124510_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Innovation.Core.Entities.ApplicationSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ApplicationSetting");
                });

            modelBuilder.Entity("Innovation.Core.Entities.KbTogether", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FormulationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LineId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Barcode");

                    b.ToTable("KbTogether");
                });

            modelBuilder.Entity("Innovation.Core.Entities.OnHand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OnHand");
                });

            modelBuilder.Entity("Innovation.Core.Entities.ProdstdMixtemp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MixPattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlanId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Temperature")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("ProdstdMixtemp");
                });

            modelBuilder.Entity("Innovation.Core.Entities.RmBal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("RawMaterialBarcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RawMaterialBarcode")
                        .IsUnique();

                    b.ToTable("RmBal");
                });

            modelBuilder.Entity("Innovation.Core.Entities.SendStepParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("LineId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlcAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StepNo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SendStepParameter");
                });

            modelBuilder.Entity("Innovation.Core.Entities.SiloApprove", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Approved")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LineId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Barcode");

                    b.ToTable("SiloApprove");
                });

            modelBuilder.Entity("Innovation.Core.Entities.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LineId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Station");
                });

            modelBuilder.Entity("Innovation.Core.Entities.TotalWeight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("KbTogetherId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SavedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalActualWeight")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KbTogetherId")
                        .IsUnique();

                    b.ToTable("TotalWeight");
                });

            modelBuilder.Entity("Innovation.Core.Entities.TrayBarcode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TypeTrayId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .IsUnique();

                    b.ToTable("TrayBarcode");
                });

            modelBuilder.Entity("Innovation.Core.Entities.TrayPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("KbTogetherId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PlannedWeight")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TrayBarcodeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TrayPlan");
                });

            modelBuilder.Entity("Innovation.Core.Entities.TrayWeight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ActualWeight")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("TrayPlanId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("WeighedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TrayWeight");
                });

            modelBuilder.Entity("Innovation.Core.Entities.TwAcceptWeightHis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AcceptedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("AcceptedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AcceptedWeight")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("StepNo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalWeightId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TwAcceptWeightHis");
                });

            modelBuilder.Entity("Innovation.Core.Entities.TypeTray", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MaxCapacity")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TypeTray");
                });

            modelBuilder.Entity("Innovation.Core.Entities.UsrWt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProgramId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LoginName")
                        .IsUnique();

                    b.ToTable("UsrWt");
                });

            modelBuilder.Entity("Innovation.Core.Entities.Weighting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Accepted")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ActualWeight")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("KbTogetherId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawMaterialCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StepNo")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TargetWeight")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Weighting");
                });
#pragma warning restore 612, 618
        }
    }
}
